version: 0.2
env:
  parameter-store:
    PS_AWS_ACCESS_KEY_ID: /prod/aws_access_key_id
    PS_AWS_SECRET_ACCESS_KEY: /prod/aws_secret_access_key
    PROD_AWS_ACCOUNT_ID: /prod/aws_account_id
    PROD_ECR_REPO_NAME: /prod/ecr_repo_name
phases:
  install:
    runtime-versions:
      docker: 18  
    commands:
      - echo "Install aws cli and boto3 "
      - apt-get update
      - apt-get install -y awscli
      - pip install boto3

  pre_build:
    commands:
      - docker build -t mysecretapp . 

  build:
    commands:
      - docker build -t mysecretapp . 
      
  post_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Build completed on `date`
      - echo Push Image to ECR
      - docker tag mysecretapp:latest ${PROD_AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${PROD_ECR_REPO_NAM}:latest
      - docker push ${PROD_AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${PROD_ECR_REPO_NAM}:latest       
