version: 0.2
env:
  parameter-store:
    PS_AWS_ACCESS_KEY_ID: /prod/aws_access_key_id
    PS_AWS_SECRET_ACCESS_KEY: /prod/aws_secret_access_key
phases:
  install:
    commands:
      - echo "Install aws cli and boto3 "
      - apt-get update
      - apt-get install -y awscli
      - pip install boto3
      - echo "Install Docker"
      - apt-get install -y docker
      - service docker start
      - docker ps
  pre_build:
    commands:
      - docker build -t mysecretapp . 

  build:
    commands:
      - docker build -t mysecretapp . 
      
  post_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Build completed on `date`
      - echo Push Image to ECR
      - docker tag mysecretapp:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/mysecretapp:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/mysecretapp:latest       
