Description: >
  "Contrast Security - Creating Task Defination"

Parameters:  
  TaskDefinitionName:
    Description: Task Defination Name
    Type: String
    Default: "CS-TaskDef"
  Environment:
    Description: "Define Environment"
    Type: String
    Default: "Dev"

Resources: 
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join
          - "" 
          -
            - !Ref Environment
            - "-taskdef-"
            - !Ref TaskDefinitionName

  ApplicationTaskDefination:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      RequiresCompatibilities:
        - "FARGATE"
      Family: !Ref 'TaskDefinitionName'
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !ImportValue ECSExceuctionRoleArn
      ContainerDefinitions: 
        - Name: !Ref 'TaskDefinitionName'
          Cpu: 256
          Memory: 512
          Image: "httpd:2.4"
          PortMappings:
            - ContainerPort: 80
          LogConfiguration: 
            LogDriver: 'awslogs'
            Options: 
              awslogs-group: !Join
                    - "" 
                    -
                      - !Ref Environment
                      - "-taskdef-"
                      - !Ref TaskDefinitionName
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: !Ref 'TaskDefinitionName'
      Tags:
       - Key: "Name"
         Value: !Join
            - ""
            -  
              - !Ref Environment
              - "-"
              - !Ref TaskDefinitionName
Outputs:
  ApplicationTaskDefination:
    Description: Application Task Defination
    Value: !Ref ApplicationTaskDefination
    Export:
      Name: ApplicationTaskDefination              
  TaskDefinitionName:
    Description: Application Task Defination Name
    Value: !Ref TaskDefinitionName
    Export:
      Name: TaskDefinitionName              
