---
Description: >
  "Contrast Security - Creating IAM Roles For Deployment"
Resources:
  CodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: codedeploy.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole

  CodeDeployInstanceProfileRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"    
      Path: "/"
      Policies:
        - 
          PolicyName: "CodeDeployInstanceRole"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: 
                  - "s3:Get*"
                  - "s3:List*"
                Resource: "*"

  CodeDeployInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles:
        - !Ref CodeDeployInstanceProfileRole

  ECSExceuctionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service: "ecs-tasks.amazonaws.com"
            Action: "sts:AssumeRole"       
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
Outputs:          
  CodeDeployRoleName:
    Description: CodeDeploy Role Name
    Value: !GetAtt CodeDeployRole.Arn
    Export: 
      Name: CodeDeployRole

  CodeDeployInstanceProfileName:
    Description: CodeDeploy Enabled Instances Role Export
    Value: !Ref CodeDeployInstanceProfile
    Export: 
        Name: CodeDeployInstanceProfile
  ECSExceuctionRoleArn:
    Description: ECS Execution Role for Task
    Value: !GetAtt ECSExceuctionRole.Arn
    Export:
      Name: ECSExceuctionRoleArn